spring:
  datasource:
    url: jdbc:duckdb:data/imdb.duckdb
    driver-class-name: org.duckdb.DuckDBDriver
imdb:
  data:
    path: data
    base-url: https://datasets.imdbws.com/
    table-names:
      - name.basics
      - title.akas
      - title.basics
      - title.crew
      - title.episode
      - title.principals
      - title.ratings
    format:
      base: tsv.gz
      target: parquet

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
